port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: info
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxy-providers:
  AKUN:
   type: file
   path: ./akun.yaml
   health-check:
   enable: true
   url: 'http://www.gstatic.com/generate_204'
   interval: '99'

proxy-groups:
- name: INTERNET
  type: select
  disable-udp: false
  url: 'https://www.gstatic.com/generate_204'
  interval: '30'
  proxies:
  - BEST-PING
  - BALANCE
  - SELECT
- name: WhatsApp
  type: select
  disable-udp: false
  url: 'https://www.gstatic.com/generate_204'
  interval: '30'
  proxies:
  - BEST-PING
  - BALANCE
  - SELECT
- name: ADS
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - INTERNET
- name: BEST-PING
  type: url-test
  disable-udp: false
  url: 'https://www.gstatic.com/generate_204'
  interval: '30'
  use:
  - AKUN
- name: BALANCE
  type: load-balance
  strategy: round-robin
  disable-udp: false
  url: 'https://www.gstatic.com/generate_204'
  interval: '30'
  use:
  - AKUN
- name: SELECT
  type: select
  disable-udp: false
  url: 'https://www.gstatic.com/generate_204'
  interval: '30'
  use:
  - AKUN
rule-providers:
  rule_hijacking:
    type: file
    behavior: classical
    path: "./rule_provider/rule_hijacking.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_hijacking.yaml
  rule_privacy:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_privacy.yaml
    path: "./rule_provider/rule_privacy.yaml"
  rule_wasapcuy:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/Xennn2605/CONFIG/refs/heads/main/rule_whatsapp.yaml
    path: "./rule_provider/rule_whatsapp.yaml"
  indo:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/Xennn2605/CONFIG/refs/heads/main/indo.yaml
    path: ./rule_provider/indo.yaml
  rule_basicads:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_basicads.yaml
    path: "./rule_provider/rule_basicads.yaml"
  rule_personalads:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_personalads.yaml
    path: "./rule_provider/rule_personalads.yaml"
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,rule_personalads,ADS
- RULE-SET,rule_wasapcuy,WhatsApp
- RULE-SET,indo,INTERNET
- RULE-SET,rule_basicads,ADS
- RULE-SET,rule_hijacking,ADS
- RULE-SET,rule_privacy,ADS
- MATCH,INTERNET
